//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Tecan.Sila2.Generator
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true, Namespace = "http://www.sila-standard.org" )]
    [System.Xml.Serialization.XmlRootAttribute( Namespace = "http://www.sila-standard.org", IsNullable = false )]
    public partial class FeatureGenerationConfig
    {

        private FeatureSpec[] featureField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Feature" )]
        public FeatureSpec[] Feature
        {
            get
            {
                return this.featureField;
            }
            set
            {
                this.featureField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( Inline ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class FeatureSpec : MemberSpec
    {

        private Inline[] inlineField;

        private PropertySpec[] propertyField;

        private CommandSpec[] commandField;

        private TypeSpec[] typeField;

        private string versionField;

        private string originatorField;

        private string categoryField;

        private FeatureMaturityLevel maturityField;

        private bool maturityFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Inline" )]
        public Inline[] Inline
        {
            get
            {
                return this.inlineField;
            }
            set
            {
                this.inlineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Property" )]
        public PropertySpec[] Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Command" )]
        public CommandSpec[] Command
        {
            get
            {
                return this.commandField;
            }
            set
            {
                this.commandField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Type" )]
        public TypeSpec[] Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Originator
        {
            get
            {
                return this.originatorField;
            }
            set
            {
                this.originatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FeatureMaturityLevel Maturity
        {
            get
            {
                return this.maturityField;
            }
            set
            {
                this.maturityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaturitySpecified
        {
            get
            {
                return this.maturityFieldSpecified;
            }
            set
            {
                this.maturityFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class Inline : FeatureSpec
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class PropertySpec : MemberSpec
    {

        private TypeMapping mappingField;

        private bool observableField;

        private bool observableFieldSpecified;

        private bool lazyField;

        private bool lazyFieldSpecified;

        private bool asMethodField;

        private bool asMethodFieldSpecified;

        /// <remarks/>
        public TypeMapping Mapping
        {
            get
            {
                return this.mappingField;
            }
            set
            {
                this.mappingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Observable
        {
            get
            {
                return this.observableField;
            }
            set
            {
                this.observableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObservableSpecified
        {
            get
            {
                return this.observableFieldSpecified;
            }
            set
            {
                this.observableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Lazy
        {
            get
            {
                return this.lazyField;
            }
            set
            {
                this.lazyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LazySpecified
        {
            get
            {
                return this.lazyFieldSpecified;
            }
            set
            {
                this.lazyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AsMethod
        {
            get
            {
                return this.asMethodField;
            }
            set
            {
                this.asMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AsMethodSpecified
        {
            get
            {
                return this.asMethodFieldSpecified;
            }
            set
            {
                this.asMethodFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class TypeMapping
    {

        private Constraints constraintField;

        private Expression valueExpressionField;

        /// <remarks/>
        public Constraints Constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }

        /// <remarks/>
        public Expression ValueExpression
        {
            get
            {
                return this.valueExpressionField;
            }
            set
            {
                this.valueExpressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class PropertyMapping
    {

        private TypeMapping mappingField;

        private string propertyField;

        private string identifierField;

        private string descriptionField;

        private string displayNameField;

        private string keyField;

        /// <remarks/>
        public TypeMapping Mapping
        {
            get
            {
                return this.mappingField;
            }
            set
            {
                this.mappingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( FormatExpression ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( PropertyExpression ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public abstract partial class Expression
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class FormatExpression : Expression
    {

        private Expression[] argField;

        private string formatStringField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Arg" )]
        public Expression[] Arg
        {
            get
            {
                return this.argField;
            }
            set
            {
                this.argField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FormatString
        {
            get
            {
                return this.formatStringField;
            }
            set
            {
                this.formatStringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class PropertyExpression : Expression
    {

        private string propertyField;

        private string createMethodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreateMethod
        {
            get
            {
                return this.createMethodField;
            }
            set
            {
                this.createMethodField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( TypeSpec ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( CommandSpec ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( PropertySpec ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( FeatureSpec ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( Inline ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public abstract partial class MemberSpec
    {

        private string displayNameField;

        private string codeField;

        private string identifierField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class TypeSpec : MemberSpec
    {

        private PropertyMapping[] propertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Property" )]
        public PropertyMapping[] Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.8.3928.0" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://www.sila-standard.org" )]
    public partial class CommandSpec : MemberSpec
    {

        private PropertyMapping[] parameterField;

        private PropertyMapping intermediateResponseField;

        private PropertyMapping[] responseField;

        private bool observableField;

        private bool observableFieldSpecified;

        private string overloadField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Parameter" )]
        public PropertyMapping[] Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        /// <remarks/>
        public PropertyMapping IntermediateResponse
        {
            get
            {
                return this.intermediateResponseField;
            }
            set
            {
                this.intermediateResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Response" )]
        public PropertyMapping[] Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Observable
        {
            get
            {
                return this.observableField;
            }
            set
            {
                this.observableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObservableSpecified
        {
            get
            {
                return this.observableFieldSpecified;
            }
            set
            {
                this.observableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Overload
        {
            get
            {
                return this.overloadField;
            }
            set
            {
                this.overloadField = value;
            }
        }
    }
}
